import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
// import { RecoilRoot } from 'recoil';
import RecoilRootWrapper from './_components/RecoilRootWrapper';
import { css } from "../styled-system/css";

const font = Noto_Sans_JP({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'RSC samples',
    template: '%s | samples'
  },
  description: 'Generated by create next app',
}

const bodyStyle = css({
  height: "100vh",
  width: "100vw",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {/*
        ・内部でcreateContextを使っているためReactRootをserver componentでは直接使えない
        ・RSCが正式版になればライブラリ側でclient componentにしてくれるはず
       */}
      <RecoilRootWrapper>
        <html lang="ja">
          <body className={`${font.className} ${bodyStyle}`}>
            {children}
          </body>
        </html>
      </RecoilRootWrapper>
    </>
  )
}
